version: "3.8"

services:
  mongo:
    image: mongo:7.0  # Use a stable MongoDB version
    container_name: mongo
    restart: always
    ports:
      - "27017:27017"
    volumes:
      - mongo-data:/data/db
    command: ["mongod", "--bind_ip", "0.0.0.0"]

  app:
    image: zainab7861/zainab-sparta-app:v3  # Replace with your actual image
    container_name: app
    restart: always
    depends_on:
      - mongo
    environment:
      DB_HOST: mongodb://mongo:27017/posts  # Set the correct MongoDB URI
    ports:
      - "3000:3000"
    stdin_open: true
    tty: true  # Allows SSH-like interaction
    command: sh -c "npm install && node seeds/seed.js && npm start"

volumes:
  mongo-data:
